import { Zone } from '../types';

export const KOLHAPUR_ZONES: Zone[] = [
  {
    id: 'railway-station',
    name: 'Railway Station',
    nameMarathi: 'रेल्वे स्थानक',
    boundaries: [],
    center: { latitude: 16.7050, longitude: 74.2439 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'high',
  },
  {
    id: 'bus-stand',
    name: 'Bus Stand (CBS)',
    nameMarathi: 'मध्यवर्ती बस स्थानक',
    boundaries: [],
    center: { latitude: 16.6967, longitude: 74.2400 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'high',
  },
  {
    id: 'shahupuri',
    name: 'Shahupuri Market',
    nameMarathi: 'शाहपूरी मार्केट',
    boundaries: [],
    center: { latitude: 16.6980, longitude: 74.2350 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'medium-high',
  },
  {
    id: 'mahalaxmi',
    name: 'Mahalaxmi Temple',
    nameMarathi: 'महालक्ष्मी मंदिर',
    boundaries: [],
    center: { latitude: 16.6750, longitude: 74.2400 },
    baseFare: 30,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 40,
    demand: 'high',
  },
  {
    id: 'jyotiba',
    name: 'Jyotiba Temple',
    nameMarathi: 'ज्योतिबा मंदिर',
    boundaries: [],
    center: { latitude: 16.7200, longitude: 74.1800 },
    baseFare: 40,
    perKmRate: 14,
    perMinuteRate: 1.5,
    minimumFare: 50,
    demand: 'high',
  },
  {
    id: 'rankala',
    name: 'Rankala Lake',
    nameMarathi: 'रांकला तलाव',
    boundaries: [],
    center: { latitude: 16.6820, longitude: 74.2250 },
    baseFare: 30,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 40,
    demand: 'medium',
  },
  {
    id: 'panhala',
    name: 'Panhala Fort',
    nameMarathi: 'पन्हाळा किल्ला',
    boundaries: [],
    center: { latitude: 16.6500, longitude: 74.1000 },
    baseFare: 50,
    perKmRate: 15,
    perMinuteRate: 1.5,
    minimumFare: 60,
    demand: 'medium',
  },
  {
    id: 'khasbag',
    name: 'Khasbag Stadium',
    nameMarathi: 'खासबाग स्टेडियम',
    boundaries: [],
    center: { latitude: 16.6950, longitude: 74.2300 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'high',
  },
  {
    id: 'shivaji-udyan',
    name: 'Shivaji Udyamnagar',
    nameMarathi: 'शिवाजी उद्यान नगर',
    boundaries: [],
    center: { latitude: 16.7100, longitude: 74.2350 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'medium',
  },
  {
    id: 'sykes',
    name: 'Sykes Extension',
    nameMarathi: 'सायक्स एक्स्टेंशन',
    boundaries: [],
    center: { latitude: 16.7020, longitude: 74.2480 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'medium',
  },
  {
    id: 'ruchira',
    name: 'Ruchira Park',
    nameMarathi: 'रुचिरा पार्क',
    boundaries: [],
    center: { latitude: 16.7150, longitude: 74.2300 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'low',
  },
  {
    id: 'sangavi',
    name: 'Sangavi',
    nameMarathi: 'सांगवी',
    boundaries: [],
    center: { latitude: 16.7300, longitude: 74.2100 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'low',
  },
  {
    id: 'tarabai-park',
    name: 'Tarabai Park',
    nameMarathi: 'ताराबाई पार्क',
    boundaries: [],
    center: { latitude: 16.6900, longitude: 74.2380 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'medium',
  },
  {
    id: 'laxmipuri',
    name: 'Laxmipuri',
    nameMarathi: 'लक्ष्मीपूरी',
    boundaries: [],
    center: { latitude: 16.7080, longitude: 74.2250 },
    baseFare: 25,
    perKmRate: 12,
    perMinuteRate: 1,
    minimumFare: 30,
    demand: 'medium',
  },
];

export const POPULAR_ROUTES: { from: string; to: string; fare: number }[] = [
  { from: 'railway-station', to: 'bus-stand', fare: 35 },
  { from: 'railway-station', to: 'mahalaxmi', fare: 60 },
  { from: 'railway-station', to: 'rankala', fare: 55 },
  { from: 'railway-station', to: 'shahupuri', fare: 40 },
  { from: 'railway-station', to: 'shivaji-udyan', fare: 45 },
  { from: 'railway-station', to: 'khasbag', fare: 40 },
  { from: 'railway-station', to: 'jyotiba', fare: 80 },
  { from: 'railway-station', to: 'panhala', fare: 100 },
  { from: 'bus-stand', to: 'mahalaxmi', fare: 50 },
  { from: 'bus-stand', to: 'rankala', fare: 50 },
  { from: 'bus-stand', to: 'shahupuri', fare: 30 },
  { from: 'bus-stand', to: 'khasbag', fare: 25 },
  { from: 'bus-stand', to: 'shivaji-udyan', fare: 40 },
  { from: 'mahalaxmi', to: 'rankala', fare: 40 },
  { from: 'mahalaxmi', to: 'shahupuri', fare: 45 },
  { from: 'rankala', to: 'tarabai-park', fare: 35 },
  { from: 'khasbag', to: 'shahupuri', fare: 25 },
  { from: 'khasbag', to: 'laxmipuri', fare: 30 },
  { from: 'shivaji-udyan', to: 'sangavi', fare: 40 },
  { from: 'shivaji-udyan', to: 'ruchira', fare: 35 },
];

export const getZoneById = (id: string): Zone | undefined => {
  return KOLHAPUR_ZONES.find(zone => zone.id === id);
};

export const getFareForRoute = (fromId: string, toId: string): number | null => {
  const route = POPULAR_ROUTES.find(
    r => (r.from === fromId && r.to === toId) || (r.from === toId && r.to === fromId)
  );
  return route?.fare ?? null;
};

export const getHighDemandZones = (): Zone[] => {
  return KOLHAPUR_ZONES.filter(zone => zone.demand === 'high');
};
